Blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path,reverse
from . import views as poll_views

app_name = 'polls'
urlpatterns = [
    path('', poll_views.IndexView.as_view(), name='index'),
    path('<slug:pk>/', poll_views.DetailView.as_view(), name='detail'),
    path('<slug:pk>/results/', poll_views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', poll_views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date posted', default=timezone.now())

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Question, Choice


# def index(request):
#     latest_questions_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_questions_list': latest_questions_list
#     }
#     return render(request, 'polls/index.html', context)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions_list'

    def get_queryset(self):
        """Return five last published"""
        return Question.objects.order_by('-pub_date')[:]


# def detail(request, question_id):
#     question = Question.objects.get(id=question_id)
#     return render(request, 'polls/detail.html', {'question': question})


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You selected no choice',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
</head>
<body>
<nav>
    <a href="{% url 'polls:index'%}" class="logo">Homepage</a>
    <br>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container">
    <div class="content-wrap">
        <h3>{{ question.question_text }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id}}">
    <label for="choice{{ forloop.counter }}" style="color:green;">{{ choice.choice_text}}</label>
<br><br>
{% endfor %}
    <input type="submit" value="Vote" >
</form>

    </div>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container">

    <div class="content-wrap">
        <h2>Click on a question to vote...</h2>
    {% if latest_questions_list %}
    <ul>
        {% for question in latest_questions_list %}
        <li ><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available</p>
    {% endif %}
    </div>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container">
    <div class="content-wrap">
        <h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}" class="btn">Vote again?</a>
    </div>
</div>
{% endblock %}